apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pawcial-backend.serviceAccountName" . }}
  namespace: pawcial
  labels:
    {{- include "pawcial-backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

