version: '3.8'

services:
  pawcial-api:
    image: 192.168.0.79:5050/mustafaguven/pawcial-backend:latest
    container_name: pawcial-api-native
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://192.168.0.58:5432/postgres
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: TS3yngKpv3P7x8
      QUARKUS_HTTP_PORT: 8000
      QUARKUS_HTTP_CORS_ORIGINS: "http://localhost:5173,http://192.168.0.72:3000"
      QUARKUS_FLYWAY_MIGRATE_AT_START: "true"
      QUARKUS_FLYWAY_BASELINE_ON_MIGRATE: "true"
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/q/health/live"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3
    networks:
      - pawcial-network

networks:
  pawcial-network:
    name: pawcial-shared-network
    driver: bridge